[tools]
"github:luau-lang/lute" = "0.1.0-nightly.20260401"
"github:rojo-rbx/rojo" = "v7.7.0-rc.1"
node = { version = "lts", postinstall = "corepack enable" }

[env]
_.file = { path = ".env", redact = true }
