name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  actions: read
  contents: read
  packages: read

env:
  CI: true
  HUSKY: 0

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

  test:
    needs: [lint]
    if: ${{ secrets.ROBLOX_OPEN_CLOUD_API_KEY != '' }}
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
        env:
          ROBLOX_OPEN_CLOUD_API_KEY: ${{ secrets.ROBLOX_OPEN_CLOUD_API_KEY }}
          ROBLOX_PLACE_ID: ${{ secrets.ROBLOX_PLACE_ID }}
          ROBLOX_UNIVERSE_ID: ${{ secrets.ROBLOX_UNIVERSE_ID }}
